### PR TITLE
fix: 154 sanity check for genesis block

### LINKED ISSUE #154: bug: If genesis block have an extra event the sanity check fails
Version: `v0.6.4+cdk.7`

The node check that genesis block provider have the expected event: a ForkID but It assume that must be the first event. In case that an L1InfoTreeUpdate is the first one the check fails!

## trace:
```
{"level":"error","ts":1724428936.925428,"caller":"synchronizer/synchronizer.go:594","msg":"error getting rollupInfoByBlockRange after set the genesis. Expected ForkIDsOrder, got L1InfoTreeOrder","pid":1,"version":"0.6.4+cdk.7","stacktrace":"github.com/0xPolygonHermez/zkevm-node/synchronizer.sanityCheckForGenesisBlockRollupInfo\n\t/home/runner/work/cdk-validium-node/cdk-validium-node/synchronizer/synchronizer.go:594\ngithub.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).RequestAndProcessRollupGenesisBlock\n\t/home/runner/work/cdk-validium-node/cdk-validium-node/synchronizer/synchronizer.go:566\ngithub.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processGenesis\n\t/home/runner/work/cdk-validium-node/cdk-validium-node/synchronizer/synchronizer.go:374\ngithub.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync\n\t/home/runner/work/cdk-validium-node/cdk-validium-node/synchronizer/synchronizer.go:412\nmain.runSynchronizer\n\t/home/runner/work/cdk-validium-node/cdk-validium-node/cmd/run.go:402"}
```

### PR DESCRIPTION
**Pull request by joanestebanr**
closes #154

### CODE REVIEW

File: synchronizer/synchronizer.go [hunk 1]
```diff
@@ -562,12 +563,18 @@ func (s *ClientSynchronizer) RequestAndProcessRollupGenesisBlock(dbTx pgx.Tx, la
 		log.Error("error getting rollupInfoByBlockRange after set the genesis: ", err)
 		return err
 	}
-	// Check that the response is the expected. It should be 1 block with 2 orders
+	// Check that the response is the expected. It should be 1 block with ForkID event
+	log.Debugf("genesis block (%d) events: %+v", lastEthBlockSynced.BlockNumber, order)
```
Comment (Stefan-Ethernal) [inline synchronizer/synchronizer.go]:
```suggestion
	log.Debugf("Genesis block (%d) events: %+v", lastEthBlockSynced.BlockNumber, order)
```

File: synchronizer/synchronizer.go [hunk 2]
```diff
@@ -562,12 +563,18 @@ func (s *ClientSynchronizer) RequestAndProcessRollupGenesisBlock(dbTx pgx.Tx, la
...
 	err = sanityCheckForGenesisBlockRollupInfo(blocks, order)
 	if err != nil {
 		return err
 	}
-	forkId := s.state.GetForkIDByBlockNumber(blocks[0].BlockNumber)
+	log.Infof("Processing genesis block %d orders: %+v", lastEthBlockSynced.BlockNumber, order)
```
Comment (Stefan-Ethernal) [inline synchronizer/synchronizer.go:572]: Do we want to keep this log, since we have the similar debug log a couple of lines before? Maybe consider putting that one to info... WDYT?

File: synchronizer/synchronizer.go [hunk 3]
```diff
@@ -562,12 +563,18 @@ func (s *ClientSynchronizer) RequestAndProcessRollupGenesisBlock(dbTx pgx.Tx, la
...
+	err = s.internalProcessBlock(blocks[0], order[blocks[0].BlockHash], false, dbTx)
+	if err != nil {
+		log.Error("error processinge events on genesis block %d:  err:%w", lastEthBlockSynced.BlockNumber, err)
```
Comment (Stefan-Ethernal) [inline synchronizer/synchronizer.go]: Should we use `Errorf` here perhaps?

```suggestion
		log.Errorf("error processinge events on genesis block %d: err:%w", lastEthBlockSynced.BlockNumber, err)
```

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by rachit77 — APPROVED** [review]

File: synchronizer/synchronizer.go (hunk 2 above)
Comment (joanestebanr) [reply synchronizer/synchronizer.go:572]: I change the previous one, need to specify that is before sanitycheck and the info one is for real process

**Comment by Melchizedek1890** [comment]
nice
